version: '3'
services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    env_file:
      - .env
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  telemirror:
    build: .
    restart: unless-stopped
    environment:
      DATABASE_URL: "postgres://${DB_USER}:${DB_PASS}@postgres/${DB_NAME}"
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres

volumes:
  database: